export const CERTIFICATES = [
  {
    id: '01',
    title: 'Programming with JavaScript',
    subtitle: 'Understanding JavaScript',
    badgeText: 'CERTIFICATE',
    recipient: 'Muhammad Talha',
    achievement: 'Completed the JavaScript course and demonstrated proficiency in core concepts, including variables, functions, and DOM manipulation.',
    issuer: 'By Meta',
    date: '2025/08/07',
    certId: 'CERT-2025-9941',
    skills: ['HTML', 'CSS', 'JavaScript'],
    link: 'https://www.coursera.org/account/accomplishments/certificate/GR352FGNLPZQ',
    cardColor: '#f7f5ee',
  },
  {
    id: '02',
    title: 'Front-End Development',
    subtitle: 'Advanced Web Development',
    badgeText: 'CERTIFICATE',
    recipient: 'Muhammad Talha',
    achievement: 'Completed the Front-End Development course, showcasing expertise in building responsive web applications and implementing modern design principles.',
    issuer: 'By Meta',
    date: '2025/07/23',
    certId: 'CERT-2026-8820',
    skills: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    link: 'https://www.coursera.org/account/accomplishments/certificate/O330NVEJJ1RS',
    cardColor: '#e8e4d8',
  },
  {
    id: '03',
    title: 'HTML and CSS in depth',
    subtitle: 'Mastering Web Design',
    badgeText: 'CERTIFICATE',
    recipient: 'Muhammad Talha',
    achievement: 'Mastered HTML and CSS, creating responsive and visually appealing web designs',
    issuer: 'By Meta',
    date: '2025/057/16',
    certId: 'CERT-2026-1103',
    skills: ['HTML', 'CSS', 'Responsive Design'],
    link: 'https://www.coursera.org/account/accomplishments/certificate/A0EQ41P43NG7',
    cardColor: '#d9d2c1',
  },
   {
    id: '04',
    title: 'Programming in Python',
    subtitle: 'Python Programming Fundamentals',
    badgeText: 'CERTIFICATE',
    recipient: 'Muhammad Talha',
    achievement: 'Completed the Python Programming course, demonstrating proficiency in Python syntax, data structures, and problem-solving techniques.',
    issuer: 'By Meta',
    date: '2026/07/07',
    certId: 'CERT-2026-1104',
    skills: ['Python', 'Data Structures', 'Problem Solving'],
    link: 'https://www.coursera.org/account/accomplishments/certificate/S7GIQJ5AZK4X',
    cardColor: '#d9d2b3',
  },
   {
    id: '05 ',
    title: 'Generative AI',
    subtitle: 'Exploring AI and Machine Learning',
    badgeText: 'CERTIFICATE',
    recipient: 'Muhammad Talha',
    achievement: 'Completed the Generative AI course, demonstrating proficiency in AI concepts and applications.',
    issuer: 'By DeepLearning.AI',
    date: '2026/10/06',
    certId: 'CERT-2026-1105',
    skills: ['Automation', 'Generative AI', 'Data Ethics'],
    link: 'https://www.coursera.org/account/accomplishments/certificate/4AYLNV8EOZJZ',
    cardColor: '#d9d4c9',
  },
   {
    id: '06',
    title: 'Git and GitHub',
    subtitle: 'Version Control & Collaboration',
    badgeText: 'CERTIFICATE',
    recipient: 'Muhammad Talha',
    achievement: 'Completed the Git and GitHub course, demonstrating proficiency in version control and collaboration.',
    issuer: 'By Meta',
    date: '2026/06/30',
    certId: 'CERT-2026-13204',
    skills: ['Git', 'GitHub', 'Version Control'],
    link: 'https://www.coursera.org/account/accomplishments/certificate/QBLQZGHT0UXQ',
    cardColor: '#d1d2c1',
  },
]