export const CERTIFICATES = [
  {
    id: '01',
    title: 'Full-Stack Web Dev',
    subtitle: 'University Certification',
    badgeText: 'CERTIFICATE',
    recipient: 'Muhammad Talha',
    achievement: 'Completed Advanced Web Architecture & Databases',
    issuer: 'Academic Institution',
    date: '2025/11/15',
    certId: 'CERT-2025-9941',
    skills: ['React', 'Node.js', 'Express', 'SQL'],
    link: 'https://github.com/muhammad-talha236',
    cardColor: '#f7f5ee',
  },
  {
    id: '02',
    title: 'JS & Algorithms',
    subtitle: 'Advanced Computer Science',
    badgeText: 'ACHIEVEMENT',
    recipient: 'Muhammad Talha',
    achievement: 'Optimized Graph Traversal & Finite Automata Logic',
    issuer: 'CS Department Board',
    date: '2026/02/10',
    certId: 'CERT-2026-8820',
    skills: ['JavaScript', 'Algorithms', 'Discrete Math'],
    link: 'https://github.com/muhammad-talha236',
    cardColor: '#e8e4d8',
  },
  {
    id: '03',
    title: 'UI/UX & Motion Dev',
    subtitle: 'Creative Frontend Design',
    badgeText: 'AWARD',
    recipient: 'Muhammad Talha',
    achievement: 'Designed Immersive Web Animations & Smooth Scroll Layouts',
    issuer: 'Design & Code Guild',
    date: '2026/05/20',
    certId: 'CERT-2026-1104',
    skills: ['GSAP', 'Tailwind CSS', 'Framer Motion'],
    link: 'https://github.com/muhammad-talha236',
    cardColor: '#d9d2c1',
  },
]